/* 
  *   Speech.java generated by speechmod 
 */
package scxmlgen.Modalities;

import scxmlgen.interfaces.IModality;

public enum Speech implements IModality {
    NOW("[confidence][THIS][EMP][EMP][EMP][EMP][EMP][EMP][EMP]", 4000);

    private String event;
    private int timeout;

    Speech(String m, int time) {
        event = m;
        timeout = time;
    }

    @Override
    public int getTimeOut() {
        return timeout;
    }

    @Override
    public String getEventName() {
        return event;
    }

    @Override
    public String getEvName() {
        return getModalityName().toLowerCase() + event.toLowerCase();
    }

}
